[default]
workshop = [
    "450814997", # CBA_A3
]
# mission = "test.VR"
mission = "DSC_Livonia.enoch"

[developer]
extends = "default"
workshop = [
    "3499977893", # Advanced Developer Tools
    "1779063631", # Zeus Enhanced
    "623475643", # Eden Enhanced
]

[developer_aegis]
extends = "developer"
dlc = [
    "Western Sahara"
]
workshop = [
    "949252631", # Aegis Mod
]

[play_test_aegis]
extends = "developer_aegis"
workshop = [
    "333310405", # Enhanced Movement
    "632435682", # Remove Stamina
    "2034363662", # Enhanced Movement Rework
    "1638341685", # DUI - Squad Radar
    "338988835", # MCC
    "2791403093", # Better Inventory
    "2884936024", # Blastcore Compiled
    "1770265310", # No More Aircraft Bouncing
    "2041057379", # A3 Thermal Improvement
    "3407948300", # JSRS Soundmod 2025
]

[play_test_rhs]
extends = "developer"
workshop = [
    "843577117", # RHSUSAF
    "843425103", # RHSAFRF
    "843593391", # RHSGREF
    "843632231", # RHSSAF
    "333310405", # Enhanced Movement
    "632435682", # Remove Stamina
    "2034363662", # Enhanced Movement Rework
    "1638341685", # DUI - Squad Radar
    "338988835", # MCC
    "2791403093", # Better Inventory
    "2884936024", # Blastcore Compiled
    "1770265310", # No More Aircraft Bouncing
    "2041057379", # A3 Thermal Improvement
    "3407948300", # JSRS Soundmod 2025
]