name = "Dynamic SOF Campaign"
prefix = "DSC"
mainprefix = "z"

[files]
include = [
    "README*.md"
]

[properties]
author = "Acorn"
url = "https://github.com/aconn1994/Dynamic_SOF_Campaign_A3"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0